; Godot MCP e2e test project — generated by e2e/run.mjs, disposable
config_version=5

[application]

config/name="mcp_e2e"
config/features=PackedStringArray("{FEATURES}")
config/icon="res://icon.svg"

[editor_plugins]

enabled=PackedStringArray("res://addons/godot_mcp/plugin.cfg")
