/**
 * The API reference is generated from the tool definitions, not written by hand.
 *
 * A hand-written page for 163 tools is stale the day after it is written, and
 * wrong documentation is worse than none: an agent that reads a parameter name
 * which no longer exists spends its turn on a call that cannot work. Everything
 * here therefore comes from the same objects the server registers, and
 * `tests/api-docs.test.ts` fails when the checked-in files drift from them.
 *
 * The examples come from `e2e/blocks/*.json`, which is the other half of the
 * point. Invented examples are a second thing to keep true; those arguments are
 * executed against a live editor on every CI run, so an example that stops
 * working fails the suite before it can mislead anyone.
 *
 * This module is pure — it takes the examples as data and returns file contents
 * — so the freshness test can render without touching the filesystem.
 */

import { categoriesByName, CORE_CATEGORIES, CategoryName } from "../registry.js";
import { ToolDefinition } from "../types/index.js";

/** Where a tool's example arguments were taken from. */
export interface ToolExample {
  /** Repo-relative block file, e.g. "e2e/blocks/03-node.json". */
  file: string;
  /** Test id such as "N-01", or null when the call is a setup/cleanup step. */
  id: string | null;
  args: unknown;
}

/** Human-facing titles for the category slugs used in `GODOT_MCP_CATEGORIES`. */
const CATEGORY_TITLES: Record<CategoryName, string> = {
  project: "Project",
  scene: "Scene",
  node: "Node",
  script: "Script",
  editor: "Editor",
  input: "Input",
  runtime: "Runtime",
  animation: "Animation",
  "animation-tree": "AnimationTree",
  "scene-3d": "3D scene",
  physics: "Physics",
  particles: "Particles",
  navigation: "Navigation",
  audio: "Audio",
  tilemap: "TileMap",
  theme: "Theme / UI",
  shader: "Shader",
  resource: "Resource",
  batch: "Batch / refactor",
  analysis: "Analysis",
  testing: "Testing / QA",
  profiling: "Profiling",
  export: "Export",
};

const GENERATED_BY =
  "<!-- Generated by server/src/docs/generate.ts. Do not edit by hand: " +
  "run `npm run docs` in server/ and commit the result. -->";

/**
 * Render every page of the reference.
 * @returns file name (relative to docs/api/) → markdown
 */
export function renderApiReference(examples: Map<string, ToolExample>): Map<string, string> {
  const pages = new Map<string, string>();
  const names = Object.keys(categoriesByName) as CategoryName[];

  for (const name of names) {
    pages.set(`${name}.md`, renderCategory(name, examples));
  }
  pages.set("README.md", renderIndex(names));
  return pages;
}

function toolsOf(name: CategoryName): [string, ToolDefinition][] {
  return Object.entries(categoriesByName[name]) as [string, ToolDefinition][];
}

function renderIndex(names: CategoryName[]): string {
  const total = names.reduce((n, c) => n + toolsOf(c).length, 0);
  const core = new Set<string>(CORE_CATEGORIES);

  const out: string[] = [
    GENERATED_BY,
    "",
    `# API reference`,
    "",
    `${total} tools in ${names.length} categories. Every tool is listed with its parameters and a`,
    "worked example; the examples are the arguments the end-to-end suite sends to a real editor,",
    "so they are executable rather than illustrative.",
    "",
    "A client can register a subset — see [Trimming the tool list](../../README.md#trimming-the-tool-list).",
    "The **core** column is what `GODOT_MCP_PROFILE=core` keeps.",
    "",
    "| Category | Tools | core | Slug for `GODOT_MCP_CATEGORIES` |",
    "|---|---:|:---:|---|",
  ];

  for (const name of names) {
    const n = toolsOf(name).length;
    const mark = core.has(name) ? "yes" : "—";
    out.push(`| [${CATEGORY_TITLES[name]}](${name}.md) | ${n} | ${mark} | \`${name}\` |`);
  }

  out.push("", "## Every tool", "", "| Tool | Category | What it does |", "|---|---|---|");
  const rows: string[] = [];
  for (const name of names) {
    for (const [toolName, tool] of toolsOf(name)) {
      rows.push(
        `| [\`${toolName}\`](${name}.md#${anchor(toolName)}) | ${CATEGORY_TITLES[name]} | ${cell(tool.description)} |`
      );
    }
  }
  rows.sort();
  out.push(...rows, "");
  return out.join("\n");
}

function renderCategory(name: CategoryName, examples: Map<string, ToolExample>): string {
  const tools = toolsOf(name);
  const inCore = CORE_CATEGORIES.includes(name);

  const out: string[] = [
    GENERATED_BY,
    "",
    `# ${CATEGORY_TITLES[name]} tools`,
    "",
    `${tools.length} tool${tools.length === 1 ? "" : "s"}. ` +
      (inCore
        ? "Registered under `GODOT_MCP_PROFILE=core`."
        : "Not registered under `GODOT_MCP_PROFILE=core`; ask for it by name with " +
          `\`GODOT_MCP_CATEGORIES=${name}\`.`),
    "",
    "[← All categories](README.md)",
    "",
  ];

  for (const [toolName, tool] of tools) {
    out.push(...renderTool(toolName, tool, examples.get(toolName)));
  }
  return out.join("\n");
}

function renderTool(
  toolName: string,
  tool: ToolDefinition,
  example: ToolExample | undefined
): string[] {
  const out: string[] = [`## \`${toolName}\``, "", tool.description, ""];

  const bounds = versionBounds(tool);
  if (bounds) out.push(bounds, "");

  const props = (tool.inputSchema?.properties ?? {}) as Record<string, Record<string, unknown>>;
  const required = new Set(tool.inputSchema?.required ?? []);
  const entries = Object.entries(props);

  if (entries.length === 0) {
    out.push("Takes no parameters.", "");
  } else {
    out.push("| Parameter | Type | Required | Description |", "|---|---|:---:|---|");
    for (const [param, schema] of entries) {
      out.push(
        `| \`${param}\` | ${typeName(schema)} | ${required.has(param) ? "yes" : "—"} | ${describe(schema)} |`
      );
    }
    out.push("");
  }

  if (example) {
    const where = example.id
      ? `\`${example.file}\`, test ${example.id}`
      : `\`${example.file}\` (setup step)`;
    out.push(
      `**Example** — the call the suite makes, from ${where}:`,
      "",
      "```json",
      JSON.stringify(example.args ?? {}, null, 2),
      "```",
      ""
    );
  }

  return out;
}

function versionBounds(tool: ToolDefinition): string | null {
  const { minGodotVersion: min, maxGodotVersion: max } = tool;
  if (min && max) return `Requires Godot ${min}–${max}.`;
  if (min) return `Requires Godot ${min} or newer.`;
  if (max) return `Requires Godot ${max} or older.`;
  return null;
}

/** JSON Schema `type`, which may be a list — rendered without a table-breaking pipe. */
function typeName(schema: Record<string, unknown>): string {
  const t = schema.type;
  const names = Array.isArray(t) ? t : typeof t === "string" ? [t] : [];
  if (names.length === 0) return "any";
  return names.map((n) => `\`${String(n)}\``).join(", ");
}

function describe(schema: Record<string, unknown>): string {
  const parts: string[] = [];
  if (typeof schema.description === "string") parts.push(schema.description);

  const values = schema.enum;
  if (Array.isArray(values) && values.length > 0) {
    parts.push(`One of: ${values.map((v) => `\`${JSON.stringify(v)}\``).join(", ")}.`);
  }
  const items = schema.items as Record<string, unknown> | undefined;
  if (items && typeof items.type === "string") {
    parts.push(`Array items are \`${items.type}\`.`);
  }
  return cell(parts.join(" ")) || "—";
}

/** Make a string safe inside a markdown table cell. */
function cell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

/** GitHub's anchor for a `### \`name\`` heading: backticks dropped, lowercased. */
function anchor(toolName: string): string {
  return toolName.toLowerCase();
}
